name: conan-promote
author: Dmitry Arkhipov <grisumbras@gmail.com>
description: GitHub Action that promotes a Conan package from one user/channel to another
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  name:
    description: Source package name
  version:
    description: Source package description
  channel:
    description: Source package channel
  user:
    description: Source package user
  reference:
    description: Full source package reference
  target-channel:
    description: Target package channel
    default: stable
  target-user:
    description: Target package user
  login:
    description: Username to authenticate as
  password:
    description: Password to use to authenticate
  url:
    description: URL of the Conan remote to upload to
  remote:
    description: Name of the Conan remote to upload to
  install:
    description: what version of Conan to install
    required: false
    default: latest
runs:
  using: node12
  main: main.js
