= conan-promote
:toc: preamble

[link=https://github.com/grisumbras/conan-promote/actions]
image::https://github.com/grisumbras/conan-promote/workflows/ci/badge.svg[Build status]

____
GitHub Action that promotes a Conan package from one user/channel to another
____


== Usage
The action promotes a Conan package from one user/channel to another using
`conan copy`.

Example usage:

[source,yaml]
----
uses: grisumbras/conan-copy@latest
----


== Inputs

=== `name`
Name of the package to promote. If not specified, `name` attribute of the
package recipe is used.

=== `version`
Version  of the package to promote. If not specified, `version` attribute of the
package recipe is used.

=== `user`
User (namespace) of the package to promote. If not specified

. `CONAN_USERNAME` environment variable is used, if present;
. or `default_user` attribute of the package recipe is used, if present;
. or the first part of the value of `GITHUB_REPOSITORY` environment variable
  (before the slash) is used.

=== `channel`
Channel of the package to promote. If not specified

. `CONAN_CHANNEL` environment variable is used, if present;
. or `default_channel` attribute of the package recipe is used, if present;
. or the string `testing`.

=== `reference`
Full reference of the package to promote. If specified all inputs that specify
parts of the reference are ignored.

=== `target-channel`
Channel to promote to. Default is `stable`.

=== `target-user`
User (namespace) to promote to. If not specified, equals to `user`.


== Maintainer
Dmitry Arkhipov <grisumbras@gmail.com>


== Contributing
Patches welcome!


== License
link:LICENSE[BSL-1.0] (C) 2019 Dmitry Arkhipov
